### ISSUE TITLE
Class GetAccountBalance not found

### ISSUE THREAD

**Issue by mostafasoufi** [infobip/infobip-api-php-client#17]
Hi,

I've try to initializing get account balance, but i can't success. because getting the below error:

`Fatal error: Class 'infobip\api\client\GetAccountBalance' not found`

The code:
```
try {
	$client = new infobip\api\client\GetAccountBalance( new infobip\api\configuration\BasicAuthConfiguration( 'username', 'password' ) );
} catch ( Exception $e ) {
	return $e->getMessage();
}
```

**Comment by hkozacinski** [comment]
Hi @mostafasoufi!
The error is present because you did not include the following line in your class:
`require_once __DIR__ . '/../../vendor/autoload.php';`
You may have simply forgotten to include it, or did not follow the part in tutorial related to using Composer. Please, refer to our readme file regarding this, specifically the [Installation](https://github.com/infobip/infobip-api-php-client/blob/master/README.md#installation) and [Basic messaging example](https://github.com/infobip/infobip-api-php-client/blob/master/README.md#basic-messaging-example) paragraphs.
Also, in the examples directory of our project, there is a working example code for your use case, named **get_account_balance_example.php**.

Kind regards

**Comment by mostafasoufi** [comment]
I really wondered why I forgot to include `vendor/autoload.php` in the class.

Thank @hkozacinski.
