### ISSUE TITLE
Delivery Reports only showing a chunk of reports. 

### ISSUE THREAD

**Issue by mahmudtopu3** [infobip/infobip-api-php-client#42]
infobip-api-php-client/infobip/examples/pull_sent_delivery_reports_example.php 
Only generates a chunk of report but how to get all reports?

**Comment by ivan-letenko** [comment]
Hi!
[Get outbound SMS message delivery reports](https://www.infobip.com/docs/api#channels/sms/get-outbound-sms-message-delivery-reports) API endpoint will return only new reports that arrived since the last API request.
Please check[ Get outbound SMS message logs](https://www.infobip.com/docs/api#channels/sms/get-outbound-sms-message-logs) method, it's designed for displaying logs in the user interface or for some other less frequent usage.
Please note that in the last release, we vastly changed and modernized this library.
