### ISSUE TITLE
 require(C:\xampp\htdocs\IT11-FINAL-PROJECT\admin/vendor/autoload.php): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ryanng25** [infobip/infobip-api-php-client#63]

**Comment by dnumicmesa** [comment]
Hi, 
could you please provide some additional information about the error you are experiencing? It seems to us that path is wrongly formatted due to the fact that a combination of multiple OS file separators (slashes and backslashes) are shown in issue title.
Thank you for using our library!

Kind regards, Damir.
